project:
  type: website
  output-dir: docs
  
website:
  title: "Lukas Anneser"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
      - href: CV.qmd
      - href: blog/index.qmd
        text: "Blog"
        

format:
  html:
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true



