---
title: "publications"
format: html
---

- **Anneser L\***, Kappel JM\* (2025). [Conserved multisensory integration of social cues in the thalamus.](https://doi.org/10.1016/j.isci.2024.111678)  
  *iScience*, 28(1):111678. **Review** Here, Johannes Kappel and I integrate the work we did in our PhD into a larger context: So far, it is still not satisfyingly answered how social representations emerge in vertebrate brains. It was a curious observation to see that very specific sensory aspects of the social environment such as visual cues and mechanosensation via the lateral line both impinge on the same thalamic area in zebrafish. We review the evidence of dedicated "social" frequencies across different modalities and species that jointly elicit activity in subparafascicular area of the thalamus, thus potentially conveying specific social information.

- **Anneser L**, Satou C, Hotz HR, Friedrich R (2024). [Molecular organization of neuronal cell types and neuromodulatory systems in the zebrafish telencephalon.](https://doi.org/10.1016/j.cub.2023.12.003) *Current Biology*, 34, 1–15. My first postdoc paper! Here, we try and chart the cell type territory of the adult zebrafish telencephalon using single-cell sequencing and gene expression visualization. We give a comprehensive overview of the neuronal cell type repertoire, the localization of specific neuronal subtypes across the pallium and subpallium, identify potential homologies across vertebrates and map out neuromodulatory signatures (i.e., expression of specific GPCRs, neuropeptides and modulation-associated genes). 

- Gemmer A, Mirkes K, **Anneser L**, Eilers T, Kibat C, Mathuru A, Ryu S, Schuman EM (2022). [Oxytocin receptors influence the development and maintenance of social behavior in zebrafish (*Danio rerio*).](https://doi.org/10.1101/2021.06.26.449566) *Scientific Reports*, 12(4322). 