---
title: "False friends in biology"
author: "Lukas Anneser"
date: 2025-07-06
categories: [working in science, HPS]
draft: False
---

# Thought follows language
If you have ever tried to learn a new language, you might have encountered *false friends*. These words sound awfully familiar to a word in your native tongue but their meaning is completely different. Many a german has stumbled over the english word *become*, which seems kinda close to the german *bekommen* (to get), leading to the infamous joke of the german asking the waiter when he might become his schnitzel (reply: "I hope never, sir"). 

In a way, it is only natural that we try to map the meaning of words to the semantic information they evoke (which might be distinct from the semantic information they actually carry). In many cases, this might be used to progressively adapt our language to better delineate what we actually want to say - not much sense in using words that our conversation partners will associate with concepts different from what we actually want to discuss. 

All the more one would suspect this to hold true in the context of highly specialized expert languages. As new concepts are worked out, special terms are invented and defined to precisely convey the technicalities inherent to the conceptual space. However, for reasons to be discussed, this does not hold true for biology. 

# Language leads astray
Studying biology is wild. On many fronts, empiricism outpaces theory by a far margin and it is not at all apparent when this trend might change. That means that whenever a biologist finds something new - be it a genetic sequence, a protein, a cell type or some previously unknown process - they have no idea about what its characteristic features are and what it might be good for in a wider context. In many cases, whatever appeared to be a relevant characteristic inspired nomenclature.

This led to some remarkable naming decisions. Wanna take a guess what the function of the *prolactin-releasing peptide* (PrRP) might be? As a matter of fact, it appears to do quite many things, but the release of prolactin is a secondary effect at best. In [1998](https://www.nature.com/articles/30515), scientists specifically set out to find a molecule triggering the release of prolactin and found PrRP to be quite efficient *in vitro*. However, rodents models with non-functional PrRP or its cognate receptor have quite normal prolactin levels. They are, however, obese, indicating a role in metabolism rather than the control of prolactin release. 

What about another example? Where do you think parathyroid hormone 2 (Pth2) is produced? Only a fool would be believe it to be the parathyroid gland. Obviously, the cells expressing it are found either in the thalamus or, depending on the species, also the medulla-pons junction. But at the very least it is a hormone, correct? Alas, as far as we know, it does not enter the bloodstream, so it does not qualify as such. This particular protein was identified in the [90s by Ted Usdin](https://pubmed.ncbi.nlm.nih.gov/10526330/), who, back then, named it *tuberoinfundibular peptide of 39 amino acids length* (TIP39). It was identified as the endogenous ligand binding to a curious receptor found in the brain whose sequence was quite similar to that of the parathyroid hormone receptor. It was thus later re-named to convey that similarity. Take note of how that decision was made - one system was already described and well-known, so the one to be discovered later was simply baptized accordingly and a number attached. 

Another fun story is the one of parvalbumin-expressing interneurons. If you are interested in neuroscience and cortical circuits on any level, you probably have heard of the classical marker genes distinguishing the interneurons found in mammalian circuits: 

*   PV (parvalbumin)
*   CCK (cholecystokinin)
*   VIP (vasoactive intestinal peptide)
*   SST (somatostatin) 

To find these kind of markers was an amazing step forward because it helped to analyze whether different kinds of interneuron displayed particular connectivity patterns or responded only in certain situations. However, referring to interneurons by the marker they express (it is quite common to say something like "SST interneurons") might also lead to the assumption that a PV interneuron in a a chimpanzee fullfills the same function than in a rodent. It is a good hypothesis, but there are lots of idiosyncracies in different species and assumptions like these have to be carefully validated. Conversely, one might look for PV interneurons in lizards and not find any, concluding that this cell type is missing and only evolved later. In reality, PV interneurons [exist in lizards and simply do not express PV](https://www.science.org/doi/10.1126/science.abp8202). What a bummer, when the gene the cell type is named after is simply not expressed. 

# A map needs to reflect the territory

It would be easy to extend the list of examples, but I think I made my point. Biology is at a crossroads, where technical terms become unnecessarily opaque and the meaning evoked by words is not at all the meaning they carry. In specialist communities, one can get away with this for a certain period of time, but the very point of having technical terms is to make a specific concept extremely clear. Language is a kind of map that helps us navigate complex conceptual territories. If you encounter a map which uses the tree symbol to show roads and reverses the usual colors of land and sea, it will rather confuse you than help you get from A to B. In particular if the community making these maps doesn't even think it necessary to explain the new standard. Obviously, [the map is not the territory](https://www.lesswrong.com/w/the-map-is-not-the-territory), but it should reflect it as well as it can to be useful.

I do not have a simple solution to the widespread use of misnomers in biology. Mostly, they came into being as completely sound and rational naming decisions and later, they were not changed as to not pollute their trail through the scientific literature (it is quite the inconvenience to a proper literature search if, for example, genes of interest have been renamed repeatedly). However, as we go on, we should be careful not to muddle our thinking by using opaque words but rather seek clarity in both thought and language. 
